"""Add failed_attempts column

Revision ID: 93df2cce65d1
Revises: dd463cbe0c25
Create Date: 2023-11-10 03:41:16.555301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93df2cce65d1'
down_revision = 'dd463cbe0c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lock_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lock_until')
        batch_op.drop_column('failed_attempts')

    # ### end Alembic commands ###
