"""Add google_id column

Revision ID: dd463cbe0c25
Revises: f3834a49c19e

Create Date: 2023-11-09 13:26:49.058132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd463cbe0c25'
down_revision = 'f3834a49c19e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])  # Name the constraint
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_constraint('uq_user_email', type_='unique', columns=['email'])
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###

